export const Type = {
  ADD_TO_BASKET: "ADD_TO_BASKET",
  DECREASE_QUANTITY: "DECREASE_QUANTITY",
  SET_USER: "SET_USER",
  EMPTY_BASKET: "EMPTY_BASKET",
  ADD_TO_WISHLIST: "ADD_TO_WISHLIST",
  REMOVE_FROM_WISHLIST: "REMOVE_FROM_WISHLIST",
  TOGGLE_THEME: "TOGGLE_THEME",
  SET_AUTH_LOADING: "SET_AUTH_LOADING"
};
